version: "3.8"

services:
  # PostgreSQL Service
  db:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: passwordManagement
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  # MailHog Service
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI to view emails
    networks:
      - app-network
    volumes:
      - ./mailhog_data:/data

  # Go Backend Service
  password-manager:
    build:
      context: .
      dockerfile: password-manager/Dockerfile
    container_name: password-manager
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/passwordManagement?sslmode=disable"
      MAILHOG_HOST: "mailhog" 
      MAILHOG_PORT: "1025"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailhog
    volumes:
      - ./config.yml:/app/config.yml
    networks:
      - app-network

  
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend-password-manager/Dockerfile  
  #   container_name: frontend-password-manager
  #   ports:
  #     - "3001:80"
  #   depends_on:
  #     - password-manager
  #   networks:
  #     - app-network
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

volumes:
  db-data:
  app-data:

networks:
  app-network:
    driver: bridge
