# Stage 1: Build the React application
FROM node:16-alpine AS react-build

WORKDIR /app

# Copy package.json and install dependencies
COPY frontend-password-manager/package*.json ./
RUN npm install

# Copy the rest of the application code and build the app
COPY frontend-password-manager/ ./
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy a custom Nginx configuration file
COPY frontend-password-manager/nginx.conf /etc/nginx/conf.d/

# Copy the build files from the previous stage
COPY --from=react-build /app/build /usr/share/nginx/html

# Expose port 80 for Nginx to serve the React app
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]



